url=https://qa-practice.razvanvancea.ro/auth_ecommerce.html
expectedTitle=QA Practice | Learn with RV
email=admin@admin.com
pswd=admin123
cartURL=https://qa-practice.razvanvancea.ro/auth_ecommerce.html
item1=Cucumber
item2=Eggs
item3=Protein Powder
phno=9657863289
street=5876 next street
city=London
country=United Kingdom